### PR TITLE
ListProperties and SelectionProperty

### LINKED ISSUE #26: Add Vector Property
<a href="https://github.com/alexanderbock"></img></a> **Issue by [alexanderbock](https://github.com/alexanderbock)**
_Thursday May 05, 2016 at 21:25 GMT_
_Originally opened as https://github.com/OpenSpace/OpenSpace-Development/issues/31_

---

Define vector property as

``` cpp
template <typename T>
class VectorProperty : public TemplateProperty?<std::vector<T>> {};
```

### LINKED ISSUE #1551: ConstellationBound's SelectionProperty cannot be set from asset
Uncommenting this line yields an error: https://github.com/OpenSpace/OpenSpace/blob/4ca82fff193002154c6e89072f551dd86d0b8411/data/assets/scene/digitaluniverse/constellationbounds.asset#L24

### PR DESCRIPTION
**Pull request by WeirdRubberDuck**
- Adds an abstract `ListProperty` and a concrete `IntListPropety` and `DoubleListProperty`
- Rewrite of `SelectionProperty` so that it can be set from a list of strings
- Fix some issues in RenderableConstellationBounds
- Start writing tests for properties
- Remove unused from string conversion for all Properties, to start simplifying interface
- Fix some missing/faulty documentation for TemplateProperty

fixes #1551 
fixes #26 

~~WebGui components coming soon!~~
PR for WebGui components: OpenSpace/OpenSpace-WebGuiFrontend#28

### CODE REVIEW

**Comment by WeirdRubberDuck** [comment]
PR for WebGui components: https://github.com/OpenSpace/OpenSpace-WebGuiFrontend/pull/28

File: modules/imgui/src/renderproperties.cpp [hunk 1]
```diff
@@ -288,27 +288,85 @@ void renderStringListProperty(Property* prop, const std::string& ownerName,
...
-    }
 
     if (hasNewValue) {
         std::vector<std::string> tokens = ghoul::tokenizeString(std::string(buffer), ',');
         std::string script = "{";
         for (std::string& token : tokens) {
             if (!token.empty()) {
                 ghoul::trimWhitespace(token);
-                script += "[[" + token + "]],";
+                script += "" + token + ",";
```
Comment (alexanderbock) [inline modules/imgui/src/renderproperties.cpp:298]: - No need for the empty string here?
 - Instead of "," can be ','

File: modules/imgui/src/renderproperties.cpp [hunk 2]
```diff
@@ -288,27 +288,85 @@ void renderStringListProperty(Property* prop, const std::string& ownerName,
...
+}
+
+void renderDoubleListProperty(Property* prop, const std::string& ownerName,
+                              IsRegularProperty isRegular, ShowToolTip showTooltip,
+                              double tooltipDelay)
+{
+    ghoul_assert(prop, "prop must not be nullptr");
+    DoubleListProperty* p = static_cast<DoubleListProperty*>(prop);
+    const std::string& name = p->guiName();
+    ImGui::PushID((ownerName + "." + name).c_str());
```
Comment (alexanderbock) [inline modules/imgui/src/renderproperties.cpp:318]: Can be '.' instead of a full "."

File: modules/imgui/src/renderproperties.cpp [hunk 3]
```diff
@@ -288,27 +288,85 @@ void renderStringListProperty(Property* prop, const std::string& ownerName,
...
+}
+
+void renderIntListProperty(Property* prop, const std::string& ownerName,
+                           IsRegularProperty isRegular, ShowToolTip showTooltip,
+                           double tooltipDelay)
+{
+    ghoul_assert(prop, "prop must not be nullptr");
+    IntListProperty* p = static_cast<IntListProperty*>(prop);
+    const std::string& name = p->guiName();
+    ImGui::PushID((ownerName + "." + name).c_str());
```
Comment (alexanderbock) [inline modules/imgui/src/renderproperties.cpp:339]: Same herre

File: modules/imgui/src/renderproperties.cpp [hunk 4]
```diff
@@ -288,27 +288,85 @@ void renderStringListProperty(Property* prop, const std::string& ownerName,
...
+}
+
+void renderStringListProperty(Property* prop, const std::string& ownerName,
+                              IsRegularProperty isRegular, ShowToolTip showTooltip,
+                              double tooltipDelay)
+{
+    ghoul_assert(prop, "prop must not be nullptr");
+    StringListProperty* p = static_cast<StringListProperty*>(prop);
+    const std::string& name = p->guiName();
+    ImGui::PushID((ownerName + "." + name).c_str());
```
Comment (alexanderbock) [inline modules/imgui/src/renderproperties.cpp:360]: And here

File: src/properties/list/doublelistproperty.cpp [hunk 5]
```diff
@@ -0,0 +1,106 @@
...
+#include <openspace/json.h>
+#include <ghoul/logging/logmanager.h>
+#include <ghoul/lua/ghoul_lua.h>
+#include <ghoul/misc/misc.h>
+
+namespace {
+    constexpr const char* _loggerCat = "DoubleListProperty";
+} // namespace
+
+namespace {
```
Comment (alexanderbock) [inline src/properties/list/doublelistproperty.cpp:36]: No need to first close the anonymous namespace and then reopening it

File: src/properties/list/doublelistproperty.cpp [hunk 6]
```diff
@@ -0,0 +1,106 @@
...
+    }
+    success = true;
+    return result;
+}
+
+bool toLuaConversion(lua_State* state, std::vector<double> val) {
+    lua_createtable(state, static_cast<int>(val.size()), 0);
+
+    int i = 1;
+    for (const int& v : val) {
```
Comment (alexanderbock) [inline src/properties/list/doublelistproperty.cpp:68]: No need to take a const ref to an int;  just using `int` will be the same

File: src/properties/list/intlistproperty.cpp [hunk 7]
```diff
@@ -0,0 +1,106 @@
...
+#include <openspace/json.h>
+#include <ghoul/logging/logmanager.h>
+#include <ghoul/lua/ghoul_lua.h>
+#include <ghoul/misc/misc.h>
+
+namespace {
+    constexpr const char* _loggerCat = "IntListProperty";
+} // namespace
+
+namespace {
```
Comment (alexanderbock) [inline src/properties/list/intlistproperty.cpp:36]: Same as above

File: src/properties/list/intlistproperty.cpp [hunk 8]
```diff
@@ -0,0 +1,106 @@
...
+    }
+    success = true;
+    return result;
+}
+
+bool toLuaConversion(lua_State* state, std::vector<int> val) {
+    lua_createtable(state, static_cast<int>(val.size()), 0);
+
+    int i = 1;
+    for (const int& v : val) {
```
Comment (alexanderbock) [inline src/properties/list/intlistproperty.cpp:68]: Same as above

File: src/properties/list/stringlistproperty.cpp [hunk 9]
```diff
@@ -22,19 +22,23 @@
...
 #include <ghoul/lua/ghoul_lua.h>
 #include <ghoul/misc/misc.h>
-#include <numeric>
 
-#include <openspace/json.h>
+namespace {
+    constexpr const char* _loggerCat = "IntListProperty";
+} // namespace
 
 namespace {
```
Comment (alexanderbock) [inline src/properties/list/stringlistproperty.cpp:36]: Same as above

File: src/properties/selectionproperty.cpp [hunk 10]
```diff
@@ -24,80 +24,162 @@
...
+    std::string result = "{ ";
+    result += fmt::format("\"{}\": {}", OptionsKey, optionsJson.dump());
+    result += " }";
+    return result;
 }
 
 template <>
-std::string PropertyDelegate<TemplateProperty<std::vector<int>>>::className() {
+std::string PropertyDelegate<TemplateProperty<std::set<std::string>>>::className()
+{
```
Comment (alexanderbock) [inline src/properties/selectionproperty.cpp:154]: { can be on the same line as the declaration

**Review by alexanderbock — APPROVED** [review]
Just some minor comments 👍

**Comment by WeirdRubberDuck** [comment]
Merging this without updating the GUI has for now, as there is currently a problem with the WebGui master not being deployed
