### PR TITLE
Fix for a lot of trail related stuff

### LINKED ISSUE #625: RenderableTrailTrajectory does not go through center of spacecraft when full trail is enabled
For example when lookign at Juno and enabling the full trail for the space craft + orbit lines.  If done, they don't match up with the accurate location

Possible solution:  Having the floating position in there as well?

### LINKED ISSUE #1067: Improve renderable trail orbit fade
There is a fade property to the renderable trail orbit but it is difficult to tweak the trail length since it seems to always render the full trail to some capacity.
To be able to control how much of the full orbit the trail should render would be a nice feature.

### LINKED ISSUE #1212: Add the ability to render the grouped asteroids as individual sprites
Instead of rendering the trails, we only want to show the individual points instead that can be scaled independently

### PR DESCRIPTION
**Pull request by Arohdin**
# PR solves following issues:
#625 , #1067 , #1212 , #1472 , #2072 , #2235, #2964
As well as bug where `RenderableTrailTrajectory` didn't render all points close to the spacecraft.

## Fixes #625
Issue is that `RenderableTrailTrajectory` does not connect to spacecrafts/objects when using rendering full trail (see final results further down).

#### No fixes
https://github.com/OpenSpace/OpenSpace/assets/9076357/2a7ffe75-b331-46b0-ae37-38c7f6f7c856

Current solution contains two parts.

1. When an object is in between two trail vertices, we render a trail from the preceding vertex to the object and from the object to the vertex that comes after.

#### Using 1st part of the fix:
https://github.com/OpenSpace/OpenSpace/assets/9076357/4c39969a-4cc5-4d76-a46f-614d30bb5880

2. The first part of the fix "solves" the issue of the trail not connected to the spacecraft. However, due to the inaccuracies of the trail vertex points (float precision issue) it still looks really bad. 
To fix this we add "padding" on each sides of the spacecraft. The padding replaces X number of vertex points (default 100) **_before and after_** the spacecraft with vertex points recalculated and then rendered in model space of the spacecraft. 
In order to have a smooth transition at the border (were old and the new vertex points meet) we move each point with a factor between 0 - 1.
By doing this we get a smooth transition with accurate vertices close to the spacecraft and then less accurate, but properly transitioned and connected, vertices at the borders.

#### Using part 1 and 2 of the fix:
https://github.com/OpenSpace/OpenSpace/assets/9076357/7d662599-7444-47ad-94fc-db933f1316d8

### Demonstration
https://github.com/OpenSpace/OpenSpace/assets/9076357/c06b9802-8a11-4375-8a40-cb9323776e53

## Fixes #1067, #2072, #2235, #2235
Issues related to trail fading controls

Implemented new way of fading by using two values called `Line Length` and `Line Fade Amount`.
`Line Length` changes how much of the trail that should be  visible where 0 means no trail and 1 means all of the trail.
`Linie Fade Amount` determines how much of the visible trail should be affected by the fade. A value of 0 means no fade, a value of 0.5 means that the fade will affect 50% of the visible trail, a value of 1 means that 100% of the visible  trail will be affected by the fade.

#### `Line Length` of 1 (no fade)
image

#### `Line Length` of 0.5 (no Fade)
image

#### `Line Fade` of 0.3 (0.5 length)
image

#### `Line Length` of 1 (0.5 length)
image

## Fixes #1212, #1472

Issues related to rendering modes for `renderableOrbitalKepler`.

New implementation adds ability to render as points in addition to lines.
Similar point controls to that of `renderablePointCloud` .
image

### CODE REVIEW

File: modules/base/rendering/renderabletrailtrajectory.cpp [hunk 1]
```diff
@@ -295,90 +354,204 @@ void RenderableTrailTrajectory::update(const UpdateData& data) {
...
-            static_cast<float>(p0.x),
-            static_cast<float>(p0.y),
-            static_cast<float>(p0.z)
-        };
-        _auxiliaryVboData[1] = { 0.f, 0.f, 0.f };
-
-        // Fill the render info with the data
+
+        // Calculates all replacement points before the object
+        glm::dvec3 v = glm::dvec3(p.x, p.y, p.z);
```
Comment (alexanderbock) [inline modules/base/rendering/renderabletrailtrajectory.cpp:413]:
```suggestion
        glm::dvec3 v = p;
```

File: modules/base/rendering/renderabletrailtrajectory.cpp [hunk 2]
```diff
@@ -295,90 +354,204 @@ void RenderableTrailTrajectory::update(const UpdateData& data) {
...
+            else {
+                mult = (prePaddingDelta - i) / static_cast<double>(prePaddingDelta);
+            }
+
+            newPoint = newPoint + dv * mult;
+            _replacementPoints.push_back({
+                static_cast<float>(newPoint.x),
+                static_cast<float>(newPoint.y),
+                static_cast<float>(newPoint.z)
+                });
```
Comment (alexanderbock) [inline modules/base/rendering/renderabletrailtrajectory.cpp:448]:
```suggestion
            });
```

File: modules/base/rendering/renderabletrailtrajectory.cpp [hunk 3]
```diff
@@ -295,90 +354,204 @@ void RenderableTrailTrajectory::update(const UpdateData& data) {
...
+        if (_numberOfReplacementPoints > 0 || !_renderFullTrail) {
+            _replacementPoints.push_back({ 0.f, 0.f, 0.f });
+        }
+
+        // Calculates all replacement points after the object
+        v = glm::dvec3(p.x, p.y, p.z);
+        for (int i = 0; i < postPaddingDelta; ++i) {
+            const int floatPointIndex = _secondaryRenderInformation.first + i;
+
+            glm::dvec3 fp(
```
Comment (alexanderbock) [inline modules/base/rendering/renderabletrailtrajectory.cpp:461]:
```suggestion
            glm::dvec3 fp = glm::dvec3(
```

File: modules/base/rendering/renderabletrailtrajectory.cpp [hunk 4]
```diff
@@ -295,90 +354,204 @@ void RenderableTrailTrajectory::update(const UpdateData& data) {
...
-
-        // Fill the render info with the data
+
+        // Calculates all replacement points before the object
+        glm::dvec3 v = glm::dvec3(p.x, p.y, p.z);
+        for (int i = 0; i < prePaddingDelta; ++i) {
+            const int floatPointIndex =
+                _primaryRenderInformation.count - prePaddingDelta + i;
+
+            glm::dvec3 fp(
```
Comment (alexanderbock) [inline modules/base/rendering/renderabletrailtrajectory.cpp:418]:
```suggestion
            glm::dvec3 fp = glm::dvec3(
```

File: modules/base/rendering/renderabletrailtrajectory.cpp [hunk 5]
```diff
@@ -295,90 +354,204 @@ void RenderableTrailTrajectory::update(const UpdateData& data) {
...
+                _vertexArray[floatPointIndex].x,
+                _vertexArray[floatPointIndex].y,
+                _vertexArray[floatPointIndex].z
+            );
+
+            glm::dvec3 dp(
```
Comment (alexanderbock) [inline modules/base/rendering/renderabletrailtrajectory.cpp:424]:
```suggestion
            glm::dvec3 dp = glm::dvec3(
```

File: modules/base/rendering/renderabletrailtrajectory.cpp [hunk 6]
```diff
@@ -295,90 +354,204 @@ void RenderableTrailTrajectory::update(const UpdateData& data) {
...
+        for (int i = 0; i < postPaddingDelta; ++i) {
+            const int floatPointIndex = _secondaryRenderInformation.first + i;
+
+            glm::dvec3 fp(
+                _vertexArray[floatPointIndex].x,
+                _vertexArray[floatPointIndex].y,
+                _vertexArray[floatPointIndex].z
+            );
+
+            glm::dvec3 dp(
```
Comment (alexanderbock) [inline modules/base/rendering/renderabletrailtrajectory.cpp:467]:
```suggestion
            glm::dvec3 dp = glm::dvec3(
```

File: modules/base/rendering/renderabletrailtrajectory.cpp [hunk 7]
```diff
@@ -295,90 +354,204 @@ void RenderableTrailTrajectory::update(const UpdateData& data) {
...
+            double mult = (i == postPaddingDelta - 1) ?
+                1.0 :
+                1.0 - (postPaddingDelta - i) / static_cast<double>(postPaddingDelta);
+
+            newPoint = newPoint + dv * mult;
+            _replacementPoints.push_back({
+                static_cast<float>(newPoint.x),
+                static_cast<float>(newPoint.y),
+                static_cast<float>(newPoint.z)
+                });
```
Comment (alexanderbock) [inline modules/base/rendering/renderabletrailtrajectory.cpp:487]:
```suggestion
            });
```

File: modules/base/shaders/renderabletrail_apple_vs.glsl [hunk 8]
```diff
@@ -54,20 +59,43 @@ void main() {
...
-    // Account for a potential rolling buffer
-    modId = gl_VertexID - idOffset;
-    if (modId < 0) {
-      modId += nVertices;
-    }
+    float id = 0;
 
-    // Convert the index to a [0,1] ranger
-    float id = float(modId) / float(nVertices);
+    if(useSplitRenderMode) {
```
Comment (alexanderbock) [inline modules/base/shaders/renderabletrail_apple_vs.glsl:64]:
```suggestion
    if (useSplitRenderMode) {
```

File: modules/base/shaders/renderabletrail_apple_vs.glsl [hunk 9]
```diff
@@ -54,20 +59,43 @@ void main() {
...
+        id = float(floatingOffset + modId) / float(max(1, numberOfUniqueVertices - 1));
+    }
+    else {
+        // Account for a potential rolling buffer
+        modId = gl_VertexID - idOffset;
+        if (modId < 0) {
+          modId += nVertices;
+        }
+        
+        // Convert the index to a [0,1] ranger
```
Comment (alexanderbock) [inline modules/base/shaders/renderabletrail_apple_vs.glsl:75]:
```suggestion
        // Convert the index to a [0,1] range
```

File: modules/base/shaders/renderabletrail_apple_vs.glsl [hunk 10]
```diff
@@ -54,20 +59,43 @@ void main() {
...
+    float b0 = lineLength;
+    float b1 = lineFadeAmount;
+
+    float fadeValue = 0.0;
+    if (id <= b0) {
+        fadeValue = 0.0;
+    }
+    else if (id > b0 && id < b1) {
+        float delta = b1 - b0;
+        fadeValue = (id-b0) / delta;
```
Comment (alexanderbock) [inline modules/base/shaders/renderabletrail_apple_vs.glsl:92]:
```suggestion
        fadeValue = (id - b0) / delta;
```

File: modules/base/shaders/renderabletrail_vs.glsl [hunk 11]
```diff
@@ -55,20 +60,43 @@ void main() {
...
-    // Account for a potential rolling buffer
-    modId = gl_VertexID - idOffset;
-    if (modId < 0) {
-      modId += nVertices;
-    }
+    float id = 0;
 
-    // Convert the index to a [0,1] ranger
-    float id = float(modId) / float(nVertices);
+    if(useSplitRenderMode) {
```
Comment (alexanderbock) [inline modules/base/shaders/renderabletrail_vs.glsl:65]:
```suggestion
    if (useSplitRenderMode) {
```

File: modules/base/shaders/renderabletrail_vs.glsl [hunk 12]
```diff
@@ -55,20 +60,43 @@ void main() {
...
+        id = float(floatingOffset + modId) / float(max(1, numberOfUniqueVertices - 1));
+    }
+    else {
+        // Account for a potential rolling buffer
+        modId = gl_VertexID - idOffset;
+        if (modId < 0) {
+          modId += nVertices;
+        }
+        
+        // Convert the index to a [0,1] ranger
```
Comment (alexanderbock) [inline modules/base/shaders/renderabletrail_vs.glsl:76]:
```suggestion
        // Convert the index to a [0,1] range
```

File: modules/base/shaders/renderabletrail_vs.glsl [hunk 13]
```diff
@@ -55,20 +60,43 @@ void main() {
...
+    float b0 = lineLength;
+    float b1 = lineFadeAmount;
+
+    float fadeValue = 0.0;
+    if (id <= b0) {
+        fadeValue = 0.0;
+    }
+    else if (id > b0 && id < b1) {
+        float delta = b1 - b0;
+        fadeValue = (id-b0) / delta;
```
Comment (alexanderbock) [inline modules/base/shaders/renderabletrail_vs.glsl:93]:
```suggestion
        fadeValue = (id - b0) / delta;
```

File: modules/space/rendering/renderableorbitalkepler.cpp [hunk 14]
```diff
@@ -63,30 +70,92 @@ namespace {
...
+        openspace::properties::Property::Visibility::AdvancedUser
+    };
+
+    constexpr openspace::properties::Property::PropertyInfo MaxSizeInfo = {
+        "MaxSize",
+        "Max Size",
+        "This value controls the maximum allowed size for the points, when the max size "
+        "control feature is enabled. This limits the visual size of the points based on "
+        "the distance to the camera. The larger the value, the larger the points are "
+        "allowed to be. In the background, the computations are made by limiting the "
```
Comment (alexanderbock) [inline modules/space/rendering/renderableorbitalkepler.cpp:106]:
```suggestion
        "allowed to be. In the background, the computations are made to limit the "
```

File: modules/space/rendering/renderableorbitalkepler.cpp [hunk 15]
```diff
@@ -63,30 +70,92 @@ namespace {
...
+        "size of the angle between the CameraToPointMid and CameraToPointEdge vectors.",
+        openspace::properties::Property::Visibility::AdvancedUser
+    };
+
+    constexpr openspace::properties::Property::PropertyInfo RenderingModeInfo = {
+        "Rendering",
+        "Rendering Mode",
+        "Determines how the trail should be rendered to the screen. If 'Trail' is "
```
Comment (alexanderbock) [inline modules/space/rendering/renderableorbitalkepler.cpp:114]:
```suggestion
        "Determines how the trail should be rendered. If 'Trail' is "
```

File: modules/space/rendering/renderableorbitalkepler.cpp [hunk 16]
```diff
@@ -130,15 +199,22 @@ namespace {
...
 
         // [[codegen::verbatim(TrailFadeInfo.description)]]
         std::optional<float> trailFade;
 
+        enum class RenderingMode {
+            Trail,
+            Point
+        };
+        // [[codegen::verbatim(RenderingModeInfo.description)]]
+        std::optional<RenderingMode> renderingMode [[codegen::key("Rendering")]];
```
Comment (alexanderbock) [inline modules/space/rendering/renderableorbitalkepler.cpp:216]: Why the `codegen::key`?  Could we just name it `RenderableMode` in the asset instead?

File: modules/space/rendering/renderableorbitalkepler.cpp [hunk 17]
```diff
@@ -173,9 +305,29 @@ RenderableOrbitalKepler::RenderableOrbitalKepler(const ghoul::Dictionary& dict)
     _segmentQuality.onChange([this]() { updateBuffers(); });
     addProperty(_segmentQuality);
 
-    _appearance.lineColor = p.color;
-    _appearance.lineFade = p.trailFade.value_or(20.f);
-    _appearance.lineWidth = p.lineWidth.value_or(2.f);
+    _appearance.color = p.color;
+    _appearance.trailFade = p.trailFade.value_or(_appearance.trailFade);
+    _appearance.trailWidth = p.trailWidth.value_or(2.f);
```
Comment (alexanderbock) [inline modules/space/rendering/renderableorbitalkepler.cpp:310]:
```suggestion
    _appearance.trailWidth = p.trailWidth.value_or(_appearance.trailWidth );
```

Otherwise we might have a wrong default value if we change the default value of the property above

File: modules/space/rendering/renderableorbitalkepler.cpp [hunk 18]
```diff
@@ -173,9 +305,29 @@ RenderableOrbitalKepler::RenderableOrbitalKepler(const ghoul::Dictionary& dict)
...
+    _appearance.outlineWeight = p.outlineWeight.value_or(_appearance.outlineWeight);
+
+    if (p.renderingMode.has_value()) {
+        switch (*p.renderingMode) {
+        case Parameters::RenderingMode::Trail:
+            _appearance.renderingModes = RenderingModeTrail;
+            break;
+        case Parameters::RenderingMode::Point:
+            _appearance.renderingModes = RenderingModePoint;
+            break;
```
Comment (alexanderbock) [inline modules/space/rendering/renderableorbitalkepler.cpp:325]:
```suggestion
            case Parameters::RenderingMode::Trail:
                _appearance.renderingModes = RenderingModeTrail;
                break;
            case Parameters::RenderingMode::Point:
                _appearance.renderingModes = RenderingModePoint;
                break;
```

File: modules/space/rendering/renderableorbitalkepler.cpp [hunk 19]
```diff
@@ -267,35 +459,55 @@ void RenderableOrbitalKepler::render(const RenderData& data, RendererTasks&) {
...
-        _appearance.lineFade.maxValue() - _appearance.lineFade,
-        2.f
-    );
+    GLint* _si = _startIndex.data();
+    GLint* _ss = _segmentSize.data();
 
-    _programObject->setUniform(_uniformCache.projection, data.camera.projectionMatrix());
-    _programObject->setUniform(_uniformCache.color, _appearance.lineColor);
-    _programObject->setUniform(_uniformCache.lineFade, fade);
+    int selection = _appearance.renderingModes;
```
Comment (alexanderbock) [inline modules/space/rendering/renderableorbitalkepler.cpp:465]:
```suggestion
    const int selection = _appearance.renderingModes;
```

File: modules/space/shaders/debrisVizPoints_fs.glsl [hunk 20]
```diff
@@ -0,0 +1,63 @@
+/*****************************************************************************************
+ *                                                                                       *
+ * OpenSpace                                                                             *
+ *                                                                                       *
+ * Copyright (c) 2014-2023                                                               *
```
Comment (alexanderbock) [inline modules/space/shaders/debrisVizPoints_fs.glsl:5]:
```suggestion
 * Copyright (c) 2014-2024                                                               *
```

File: modules/space/shaders/debrisVizPoints_fs.glsl [hunk 21]
```diff
@@ -0,0 +1,63 @@
...
+    _color = outlineColor;
+  }
+
+  frag.color = vec4(_color, opacity);
+  frag.depth = projectionViewDepth;
+  frag.gPosition = viewSpace;
+  frag.gNormal = vec4(0.0, 0.0, 0.0, 1.0);
+
+  return frag;
+}
```
Comment (alexanderbock) [inline modules/space/shaders/debrisVizPoints_fs.glsl:63]:
```suggestion
}

```

File: modules/space/shaders/debrisVizPoints_gs.glsl [hunk 22]
```diff
@@ -0,0 +1,150 @@
+/*****************************************************************************************
+ *                                                                                       *
+ * OpenSpace                                                                             *
+ *                                                                                       *
+ * Copyright (c) 2014-2023                                                               *
```
Comment (alexanderbock) [inline modules/space/shaders/debrisVizPoints_gs.glsl:5]:
```suggestion
 * Copyright (c) 2014-2024                                                               *
```

File: modules/space/shaders/debrisVizPoints_gs.glsl [hunk 23]
```diff
@@ -0,0 +1,150 @@
...
+ * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,   *
+ * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A         *
+ * PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT    *
+ * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF  *
+ * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE  *
+ * OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                                         *
+ ****************************************************************************************/
+
+/*
+  NOTE:
```
Comment (alexanderbock) [inline modules/space/shaders/debrisVizPoints_gs.glsl:26]: Do we need the notes here still?

File: modules/space/shaders/debrisVizPoints_gs.glsl [hunk 24]
```diff
@@ -0,0 +1,150 @@
...
+out vec2 texCoord;
+flat out int skip;
+
+dvec4 dz_normalization(dvec4 dv_in) {
+  dvec4 dv_out = dv_in;
+  dv_out.z = 0;
+  return dv_out;
+}
+
+void main () {
```
Comment (alexanderbock) [inline modules/space/shaders/debrisVizPoints_gs.glsl:60]:
```suggestion
void main() {
```

File: modules/space/shaders/debrisVizPoints_gs.glsl [hunk 25]
```diff
@@ -0,0 +1,150 @@
...
+    // Calculate current vertex position to world space
+    dvec4 vertPosWorldSpace = modelTransform * pos;
+
+    // Calculate new axis for plane
+    dvec3 normal = normalize(cameraPositionWorld - vertPosWorldSpace.xyz);
+    dvec3 right = normalize(cross(cameraUpWorld, normal));
+    dvec3 up = normalize(cross(normal, right));
+
+    // Calculate size of points
+    double initialSize = pow(10, pointSizeExponent);
```
Comment (alexanderbock) [inline modules/space/shaders/debrisVizPoints_gs.glsl:88]:
```suggestion
    double initialSize = pow(10.0, pointSizeExponent);
```

File: modules/space/shaders/debrisVizPoints_gs.glsl [hunk 26]
```diff
@@ -0,0 +1,150 @@
...
+    //left-top
+    vec4 p0Screen = vec4(dz_normalization(ViewProjectionTransform * p0World));
+    gl_Position = p0Screen;
+    texCoord = vec2(0,0);
+    EmitVertex();
+
+    //left-bot
+    vec4 p1Screen = vec4(dz_normalization(ViewProjectionTransform * p1World));
+    gl_Position = p1Screen;
+    texCoord = vec2(1,0);
```
Comment (alexanderbock) [inline modules/space/shaders/debrisVizPoints_gs.glsl:127]:
```suggestion
    texCoord = vec2(1.0, 0.0);
```

File: modules/space/shaders/debrisVizPoints_gs.glsl [hunk 27]
```diff
@@ -0,0 +1,150 @@
...
+    EmitVertex();
+
+    //right-top
+    vec4 p2Screen = vec4(dz_normalization(ViewProjectionTransform * p2World));
+    gl_Position = p2Screen;
+    texCoord = vec2(0,1);
```
Comment (alexanderbock) [inline modules/space/shaders/debrisVizPoints_gs.glsl:133]:
```suggestion
    texCoord = vec2(0.0, 1.0);
```

File: modules/space/shaders/debrisVizPoints_gs.glsl [hunk 28]
```diff
@@ -0,0 +1,150 @@
...
+    EmitVertex();
+
+    //right-bot
+    vec4 p3Screen = vec4(dz_normalization(ViewProjectionTransform * p3World));
+    gl_Position = p3Screen;
+    texCoord = vec2(1,1);
```
Comment (alexanderbock) [inline modules/space/shaders/debrisVizPoints_gs.glsl:139]:
```suggestion
    texCoord = vec2(1.0, 1.0);
```

File: modules/space/shaders/debrisVizPoints_gs.glsl [hunk 29]
```diff
@@ -0,0 +1,150 @@
...
+    EmitVertex();
+    
+    // Primitive
+    EndPrimitive();
+
+  } else {
```
Comment (alexanderbock) [inline modules/space/shaders/debrisVizPoints_gs.glsl:145]:
```suggestion
  }
  else {
```

File: modules/space/shaders/debrisVizPoints_vs.glsl [hunk 30]
```diff
@@ -0,0 +1,49 @@
+/*****************************************************************************************
+ *                                                                                       *
+ * OpenSpace                                                                             *
+ *                                                                                       *
+ * Copyright (c) 2014-2023                                                               *
```
Comment (alexanderbock) [inline modules/space/shaders/debrisVizPoints_vs.glsl:5]:
```suggestion
 * Copyright (c) 2014-2024                                                               *
```

File: modules/space/shaders/debrisVizPoints_vs.glsl [hunk 31]
```diff
@@ -0,0 +1,49 @@
...
+layout (location = 1) in vec2 orbitData; // 1: epoch, 2: period
+
+uniform double inGameTime;
+uniform dmat4 modelTransform;
+
+flat out double currentRevolutionFraction;
+flat out double vertexRevolutionFraction;
+
+void main() {
+
```
Comment (alexanderbock) [inline modules/space/shaders/debrisVizPoints_vs.glsl:37]:
```suggestion
```

File: modules/space/shaders/debrisVizPoints_vs.glsl [hunk 32]
```diff
@@ -0,0 +1,49 @@
...
+  double numOfRevolutions = (inGameTime - epoch) / period;
+
+  vertexRevolutionFraction = vertexData.w / period;
+  currentRevolutionFraction = numOfRevolutions - double(int(numOfRevolutions));
+  if (currentRevolutionFraction < 0.0) {
+    currentRevolutionFraction += 1.0;
+  }
+
+  gl_Position = vec4(vertexData.xyz, 1.0);
+}
```
Comment (alexanderbock) [inline modules/space/shaders/debrisVizPoints_vs.glsl:49]:
```suggestion
}

```

File: modules/space/shaders/debrisVizTrails_fs.glsl [hunk 33]
```diff
@@ -46,26 +54,24 @@ Fragment getFragment() {
...
-
-  Fragment frag;
+  
+  // Use additive blending for some values to make the discarding less abrupt
   if (fade < 0.15) {
-    // Use additive blending for some values to make the discarding less abrupt
     frag.blend = BLEND_MODE_ADDITIVE;
   }
-
+
```
Comment (alexanderbock) [inline modules/space/shaders/debrisVizTrails_fs.glsl:74]:
```suggestion

```

File: tests/test_settings.cpp [hunk 34]
```diff
@@ -745,6 +745,221 @@ TEST_CASE("Settings Save: LayerServer/None", "[settings]") {
     CHECK(srcSettings == cmpSettings);
 }
 
+TEST_CASE("Settings Load: LayerServer/All", "[settings]") {
```
Comment (alexanderbock) [inline tests/test_settings.cpp:748]: Not sure where this file comes from but it probably is not part of the PR

**Review by alexanderbock — COMMENTED** [review]
Haven't run it yet, will do tomorrow

File: modules/space/rendering/renderableorbitalkepler.cpp (hunk 16 above)
Comment (Arohdin) [reply modules/space/rendering/renderableorbitalkepler.cpp:216]: I think I did this in order to keep it aligned with `renderableTrail`.
We can change this to `RenderableMode`, `RenderingMode` or `RenderModede`.
If we change for this class, should we also change for `renderableTrail`?

File: modules/base/rendering/renderabletrail.cpp [hunk 35]
```diff
@@ -448,31 +479,81 @@ void RenderableTrail::render(const RenderData& data, RendererTasks&) {
...
+            _primaryRenderInformation,
             totalNumber,
-            // -1 because we duplicate the penultimate point between the vertices
-            -(primaryOffset + _primaryRenderInformation.count - 1)
+            primaryOffset
         );
+
+        // The secondary batch is optional, so we need to check whether we have any data here
+        if (_floatingRenderInformation._vaoID != 0 && _floatingRenderInformation.count != 0) {
+            internalRender(
```
[the remark this answers is not in the document]
Comment (Arohdin) [reply modules/base/rendering/renderabletrail.cpp:542]: Not sure that I completely follow.
The `offset` variable is not needed here as it's not doing any split rendering.

File: modules/base/rendering/renderabletrail.cpp [hunk 36]
```diff
@@ -86,12 +88,26 @@ namespace {
...
+
+    constexpr openspace::properties::Property::PropertyInfo LineFadeAmountInfo = {
+        "LineFadeAmount",
+        "Line Fade Amount",
+        "The amount of the trail that should be faded. If the value is 0 the "
+        "trail will have no fading. A value of 0.5 will have a solid trail until "
+        "50% of the trail and then the fading will begin. A value of 1 will "
+        "result in a trail that starts fading immediately. The setting only "
+        "applies if the 'EnableFade' value is 'true'. If it is 'false', this "
+        "setting has no effect.",
```
[the remark this answers is not in the document]
Comment (Arohdin) [reply modules/base/rendering/renderabletrail.cpp:110]: Does this make more sense?

> "The amount of the trail that should be faded. If the value is 0 then the "
> "trail will have no fading applied. A value of 0.6 will result in a trail "
> "where 60% of the extent of the trail will have fading applied to it. In other"
> "words, the 40% closest to the source of the trail will be solid and the rest "
> "will fade until completely transparent at the end of the trail. A value of 1 "
> "will result in a trail that starts fading immediately, becoming fully "
> "transparent by the end of the trail. This setting only applies if the "
> "'EnableFade' value is 'true'. If it is 'false', this setting has no effect.",

[the remark this answers is not in the document]
Comment (alexanderbock) [reply modules/base/rendering/renderabletrail.cpp:110]: I'd say "source" -> "front" or "head" ?

Otherwise :+1:

File: modules/base/rendering/renderabletrail.cpp (hunk 35 above)
[the remark this answers is not in the document]
Comment (alexanderbock) [reply modules/base/rendering/renderabletrail.cpp:543]: Sorry, mb.

Higher up you defined:
```
int offset = (_floatingRenderInformation.count > 0) ? 1 : 0;
```

I was saying that it could be more readable to:
```
const int offset = -(primaryOffset + _primaryRenderInformation.count - 1);
```
and then use `offset` in the function call instead.  But super tiny thing

File: modules/space/rendering/renderableorbitalkepler.cpp (hunk 16 above)
Comment (alexanderbock) [reply modules/space/rendering/renderableorbitalkepler.cpp:216]: Ah.. keeping it aligned is good enough for me :+1:

**Comment by alexanderbock** [comment]
Tested and works :+1:

**Review by alexanderbock — APPROVED** [review]

**Comment by alexanderbock** [comment]
Would be good to get a third pair of eyes on it if possible

**Comment by engbergandreas** [comment]
Not sure how to test everything but I played around with the orbital trails at least and it feels intuitive to control fading/length etc.

File: tests/test_settings.cpp (hunk 34 above)
Comment (Arohdin) [reply tests/test_settings.cpp]: Fixed in: [dd833a](https://github.com/OpenSpace/OpenSpace/commit/dd833aa38af348842bee61b73159e1ce3d393ad7)

File: modules/base/rendering/renderabletrail.cpp (hunk 35 above)
[the remark this answers is not in the document]
Comment (Arohdin) [reply modules/base/rendering/renderabletrail.cpp:545]: Sorry, not seeing how this is equivalent. Is it OK to skip this for now and check it later?
