### PR TITLE
interaction sphere and brightness/opacity fixes. (Closes #1994)

### LINKED ISSUE #1994: Flying to magnetosphere brings you inside planet
Assuming that it needs a bounding and/or interaction sphere

### PR DESCRIPTION
**Pull request by ElonOlsson**
I tested removing brightness altogether but it's needed.
What do you think about having both properties in the GUI like this? Visually it's difficult to understand the difference.

### CODE REVIEW

File: modules/volume/rendering/renderabletimevaryingvolume.cpp [hunk 1]
```diff
@@ -106,7 +106,7 @@ namespace {
     constexpr openspace::properties::Property::PropertyInfo BrightnessInfo = {
         "Brightness",
         "Brightness",
-        "The volumes general brightness."
+        "The volume renderers general brightness."
```
Comment (alexanderbock) [inline modules/volume/rendering/renderabletimevaryingvolume.cpp:109]: -> renderer's

**Comment by alexanderbock** [comment]
It's not super nice to have both but i think for now it will do, imo

**Review by alexanderbock — APPROVED** [review]
